[package]
name = "cgol"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[[bin]]
name = "cgol"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
